[ADD] 메인화면 api 설계 완료(메인화면 product 개수 수정 가능성 존재)
wecode-bootcamp-korea/38-1st-JustWeDoIt-backend pull request #3
Opened 2022-10-19 14:11 UTC by iflov

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인화면 게시물 데이터 전송

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
product Table에서 10개의 product Data 전송

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
Foundation 기간에 배운 post 전체 게시물 조회를 활용
어떤 코드는 알고있는 코드는 활용하는데 두려움이 사리지게되었습니다!

<br />

## :: 기타 질문 및 특이 사항
아직 module.exports 부분 {} 쓰냐 안쓰냐 느낌을 모르겠습니다 ㅠㅠ

2022-10-21 05:30 UTC, lordmyshepherd requested changes

2022-10-21 05:30 UTC, lordmyshepherd commented on controllers/mainController.js
> +});
엔드포인트에 `Main` 이라는 키워드가 포함되어 있네요.
아마도 메인페이지에서 필요한 데이터를 반환해준다는 의미에서 `mainController`, `mainSercice`, `mainDao`로 만들어주신 것 같습니다.

엔드포인트를 구현할 때에는 자원(resource, data) 기준으로 만들어주셔야 합니다.
그래야만 프론트 페이지로부터 독립된 여러 곳에서 사용할 수 있는 엔드포인트가 될 수 있습니다.

Main이 아니라 반환되는 데이터를 기준으로 다시 수정부탁드립니다-!
예를 들어서,

```javascript
// productController.js
getProducts = () => {}

// productService.js
getProducts = () => {}

// productDao.js
..
```

2022-10-21 05:30 UTC, lordmyshepherd commented on models/mainDao.js
> +}
위에서 드린 피드백과 동일하게 `requestMain()` -> `getAllProducts()`로 만들어주세요.

2022-10-21 05:30 UTC, lordmyshepherd commented on models/mainDao.js
> +
빈 줄은 지워주세요~
```suggestion
```

2022-10-21 05:30 UTC, lordmyshepherd commented on models/mainDao.js
> +    const numberLimit = +limit;
dao에서 숫자로 변경해주기 보다는 controller에서 service로 넘겨줄 때부터 integer로 변경해서 호출해주세요.

2022-10-21 05:30 UTC, lordmyshepherd commented on models/mainDao.js
> +            WHERE products.id LIMIT ?,? `
OFFSET 키워드가 빠진 것 같은데 제대로 동작하나요?

2022-10-21 05:30 UTC, lordmyshepherd commented on models/moveProductDao.js
> +    return data;
`database.query()` 함수를 호출하면 배열 형태로 반환됩니다.
그렇기 때문에 아래와 같이 배열에 포함된 객체 하나만 꺼내서 반환해주면 함수가 반환하는 값이 더욱 명확해질 것 같습니다.

```suggestion
    const [ data ] = await database.query(`
        SELECT 
            p.id,
            p.name AS productName,
            p.description,
            p.price,
            i.image_url AS imageUrl,
            c.name AS category,
            s.name AS special,
            g.gender,
            t.size,
            t.stock
        FROM products p
        JOIN categories c ON p.category_id = c.id
        JOIN special s ON p.special_id = s.id
        JOIN gender g ON p.gender_id = g.id
        JOIN product_images i ON p.id = i.product_id
        JOIN stock t ON p.id = t.product_id
        WHERE p.id = ?
    `,
    [productId])

    return data;
```

2022-10-21 08:47 UTC, iflov commented
`self refactoring`

```javascript
const stocks = [
    {
        stoke_id : 1,
        size : "s",
        stock : 5,
        product: {
            id : 1,
            name : "s",
            images : ["https://images.unsplash.com/photo-1562183241-b937e95585b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80", "https://images.unsplash.com/photo-1518656306295-aa28b28b2504?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"]
        }
    },
    {
        stoke_id : 2,
        size : "s",
        stock : 5,
        product: {
            id : 1,
            name : "s",
            images : ["https://images.unsplash.com/photo-1562183241-b937e95585b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80", "https://images.unsplash.com/photo-1518656306295-aa28b28b2504?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"]
        }
    },
    {
        stoke_id : 3,
        size : "s",
        stock : 5,
        product: {
            id : 1,
            name : "s",
            images : []
        }
    },
]

```

2022-10-26 05:14 UTC, lordmyshepherd commented
```
function filterBuilder(criteria) {
  let sql = '';
  let fieldArr = [];

  if (criteria.length === 0) return sql;

  for (var item of criteria) {
    fieldArr.push(item.value);
    sql = fieldArr.join(item.condition);
    fieldArr = [sql];
  }
  return ` WHERE ${sql}`;
}

const queries = {
  title: 'title 입니다.',
  user_id: 1,
  minPrice: 1000,
  maxPrice: 100000,
  colors: ['red', 'blue'],
};

const criteria = [
  { field: 'title', value: `title = ${queries.title}`, condition: ' AND ' },
  {
    field: 'user_id',
    value: `user_id = ${queries.user_id}`,
    condition: ' OR ',
  },
  {
    field: 'minPrice',
    value: `price > ${queries.minPrice}`,
    condition: ' AND ',
  },
  {
    field: 'maxPrice',
    value: `price < ${queries.maxPrice}`,
    condition: ' AND ',
  },
  {
    field: 'colors',
    value: `color IN  (${queries.colors.join(',')})`,
    condition: ' AND ',
  },
];

// 사용 예
// const whereClause = filterBuilder(
//   criteria.filter((cr) => queries.hasOwnProperty(cr.field))
// );

```

2022-10-27 02:23 UTC, lordmyshepherd commented
LGTM 👍🏻 
리펙토링과 배포 부탁드립니다~~

2022-10-27 02:23 UTC, merged